version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
            - .:/app
       ports:
           - 1337:8000
       depends_on:
           - redis

   redis:
       image: redis

   celery:
       build: .
       command: celery -A anime_site worker -l info
       volumes:
           - .:/app
       depends_on:
           - redis
