# Generated by Django 5.0.6 on 2024-05-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_viewingstatus_like_anime_likes'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_anime', to='anime.anime', verbose_name='Аниме'),
        ),
    ]
