# Generated by Django 5.0.6 on 2024-05-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('alt_title', models.CharField(blank=True, max_length=255, verbose_name='Альтернативное название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('type', models.CharField(choices=[('tv_series', 'Сериал'), ('movie', 'Фильм')], max_length=10, verbose_name='Тип')),
                ('date_aired', models.DateField(verbose_name='Дата выхода в эфир')),
                ('status', models.CharField(choices=[('it_continues', 'Выходит'), ('completed', 'Завершен')], max_length=15, verbose_name='Статус')),
                ('rating', models.FloatField(blank=True, default=0, verbose_name='Рейтинг')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('views', models.PositiveIntegerField(blank=True, default=0, verbose_name='Просмотры')),
                ('cover', models.ImageField(blank=True, upload_to='anime_covers/%Y/%m', verbose_name='Обложка')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('genres', models.ManyToManyField(related_name='anime_genres', to='anime.genre', verbose_name='Жанры')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.studio', verbose_name='Студия')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
    ]
