# Generated by Django 5.0.6 on 2024-05-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_studio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('watching', 'Смотрю'), ('viewed', 'Просмотрено'), ('abandoned', 'Заброшено')], max_length=15, verbose_name='Название')),
                ('slug', models.SlugField(max_length=15, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статус просмотра',
                'verbose_name_plural': 'Статусы просмотов',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='Аниме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='anime_likes', to='anime.like'),
        ),
    ]
