# Generated by Django 5.0.6 on 2024-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_animeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
