# Generated by Django 5.0.6 on 2024-05-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_anime_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='series_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер серии'),
        ),
    ]
