# Generated by Django 5.0.6 on 2024-05-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_animeseries_series_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
