# Generated by Django 5.0.6 on 2024-05-26 02:07

import anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover',
            field=models.ImageField(blank=True, upload_to='anime_covers/%Y/%m', validators=[anime.models.validate_cover_size], verbose_name='Обложка'),
        ),
    ]
